import Splash from 'screens/splash-screen';
import LoginScreen from 'screens/login-screen';
import SignupScreen from 'screens/signup-screen';
import BirthdayOnSignup from 'screens/signup-screen/birthday';
import ForgotPassword from 'screens/forget-password';
import ResetPassword from 'screens/reset-password';
import VerifyCodeOnForgotPassword from 'screens/verify-code-on-forget-password';
import VerifyCodeOnSignup from 'screens/signup-screen/verify-code';
import UserNameOnSignup from 'screens/signup-screen/username';
import Home from 'screens/dashboard/home';
import Profile from 'screens/dashboard/profile';
import About from 'screens/dashboard/profile/About';
import EditAbout from 'screens/dashboard/profile/About/editAboutInformation';
import FollowingFollowers from 'screens/dashboard/profile/following-followers';
import Notification from 'screens/dashboard/notification';
import FollowersRequestScreen from 'screens/dashboard/notification/followers-request';
import SearchScreen from 'screens/dashboard/search';
import ChatScreen from 'screens/dashboard/chat';
import CommentScreen from 'screens/dashboard/comments';
import ChatHomeScreen from 'screens/dashboard/chatHome';
import CameraComponent from 'screens/dashboard/camera';
import canvas from 'screens/dashboard/camera/canvas';
import trimVideoScreen from 'screens/dashboard/camera/trimVideo';
import Post from 'screens/dashboard/camera/post';
import EditPost from 'screens/dashboard/camera/editPost';
import Drawer from 'screens/dashboard/drawer';
import PostView from 'screens/dashboard/profile/postViewScreen';
import viewAllUserScreen from 'screens/dashboard/search/view-all-users';
import viewAllTopUserScreen from 'screens/dashboard/search/view-all-top-users';
import publicProfileScreen from 'screens/dashboard/profile/public-profile';
import appIntro from 'screens/appIntro';
import weeklyVideoViewScreen from 'screens/dashboard/profile/weekly/weekly-video-view';
import pushNotifications from 'screens/dashboard/drawer/notifications';
import saved from './dashboard/drawer/saved';
import Privacy from 'screens/dashboard/drawer/privacy';
import about from './dashboard/drawer/about';
import privacypolicy from './dashboard/drawer/about/privacypolicy';
import legalInformation from './dashboard/drawer/about/legal-information';
import support from './dashboard/drawer/about/support';
import ManageAccount from './dashboard/drawer/manage-account';
import ChangePasswordScreen from './dashboard/drawer/manage-account/reset-password';
import DeactivateAccount from './dashboard/drawer/manage-account/deactivate-account';
import ChangeEmailScreen from './dashboard/drawer/manage-account/reset-email';
import VerifyCodeResetEmailScreen from './dashboard/drawer/manage-account/reset-email/verity';
import AccountVerification from './dashboard/drawer/manage-account/verify-account';
import VerifyProgress from './dashboard/drawer/manage-account/verify-account/verifyProgress';
import ViewAllVideos from './dashboard/search/view-all-videos';
import HashtagVideos from './dashboard/search/HashtagVideos';
import TopPostsView from './dashboard/search/postViewScreen';
import SavedViewPostView from './dashboard/drawer/savedPostView';
import ChooseUname from './signup-screen/choose-username';
import ViewAllLikedUserScreen from './dashboard/home/likes';

export const SPLASH = Splash;
export const LOGIN = LoginScreen;
export const SIGNUP = SignupScreen;
export const BirthDayOnSignUpScreen = BirthdayOnSignup;
export const ForgotPasswordScreen = ForgotPassword;
export const ResetPasswordScreen = ResetPassword;
export const VerifyCodeOnForgotPasswordScreen = VerifyCodeOnForgotPassword;
export const VerifyCodeOnSignupScreen = VerifyCodeOnSignup;
export const UserNameOnSignupScreen = UserNameOnSignup;
export const HomeScreen = Home;
export const ProfileScreen = Profile;
export const AboutScreen = About;
export const EditAboutScreen = EditAbout;
export const FollowingFollowersScreen = FollowingFollowers;
export const NotificationScreen = Notification;
export const FollowersRequest = FollowersRequestScreen;
export const Search = SearchScreen;
export const Chat = ChatScreen;
export const Comments = CommentScreen;
export const ChatHome = ChatHomeScreen;
export const CameraScreen = CameraComponent;
export const PostScreen = Post;
export const EditPostScreen = EditPost;
export const DrawerScreen = Drawer;
export const PersonalPostView = PostView;
export const TrimVideoScreen = trimVideoScreen;
export const ViewAllUserScreen = viewAllUserScreen;
export const ViewAllTopUserScreen = viewAllTopUserScreen;
export const PublicProfileScreen = publicProfileScreen;
export const WeeklyVideoViewScreen = weeklyVideoViewScreen;
export const AppIntro = appIntro;
export const PushNotificationsSettingScreen = pushNotifications;
export const PrivacyScreen = Privacy;
export const SavedScreen = saved;
export const AboutSettingScreen = about;
export const PrivacyPolicyScreen = privacypolicy;
export const LegalInformationScreen = legalInformation;
export const SupportScreen = support;
export const ManageAccountScreen = ManageAccount;
export const ResetPasswordScreenInManageAccount = ChangePasswordScreen;
export const ChangeEmailScreenInManageAccount = ChangeEmailScreen;
export const VerifyCodeEmailScreen = VerifyCodeResetEmailScreen;
export const DeactivateAccountScreen = DeactivateAccount;
export const AccountVerificationScreen = AccountVerification;
export const VerifyProgressScreen = VerifyProgress;
export const Viewallvideos = ViewAllVideos;
export const HashtagVideosScreen = HashtagVideos;
export const TopVideosView = TopPostsView;
export const SavedPostsView = SavedViewPostView;
export const ChooseUsername = ChooseUname;
export const ViewAllLikedUsers = ViewAllLikedUserScreen;
export const Canvas = canvas;
